# Generated by Django 3.1.7 on 2021-04-05 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('distance', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(choices=[('Running', 'RUNNING'), ('Biking', 'BIKING'), ('Swimming', 'SWIMMING'), ('Walking', 'WALKING')], default='running', max_length=17)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='LowerBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField(default=0)),
                ('sets', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(choices=[('Squats', 'SQUATS'), ('Lunges', 'LUNGES'), ('Calf Raises', 'CALF_RAISES'), ('Leg Press', 'LEG_PRESS'), ('Deadlifts', 'DEADLIFTS')], default='sqauts', max_length=17)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='UpperBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField(default=0)),
                ('sets', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(choices=[('Pushups', 'PUSHUPS'), ('Pullups', 'PULLUPS'), ('Back row', 'BACK_ROW'), ('Bicep curls', 'BICEP_CURLS'), ('Tricep Extensions', 'TRICEP_EXTENSIONS')], default='pushups', max_length=17)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
