# Generated by Django 3.1.6 on 2021-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running', models.CharField(max_length=10)),
                ('biking', models.CharField(max_length=10)),
                ('swimming', models.CharField(max_length=10)),
                ('walking', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LowerBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squats', models.CharField(max_length=4)),
                ('lunges', models.CharField(max_length=4)),
                ('calf_raises', models.CharField(max_length=4)),
                ('leg_press', models.CharField(max_length=4)),
                ('deadlifts', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UpperBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushups', models.CharField(max_length=4)),
            ],
        ),
    ]
