# Generated by Django 3.1.6 on 2021-04-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upperbody',
            name='pushups',
        ),
        migrations.AddField(
            model_name='upperbody',
            name='reps',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upperbody',
            name='sets',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upperbody',
            name='upper_workout',
            field=models.CharField(choices=[('pushups', 'pushups')], default='pushups', max_length=10),
        ),
    ]
