# Generated by Django 3.2 on 2021-05-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='username',
            new_name='email',
        ),
    ]
