# Generated by Django 3.2 on 2021-05-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_username_friendrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
