# Generated by Django 3.1.6 on 2021-04-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210403_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='upperbody',
            name='reps_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upperbody',
            name='sets_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
