# Generated by Django 3.1.6 on 2021-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210405_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerbody',
            name='type',
            field=models.CharField(choices=[('Squats', 'SQUATS'), ('Lunges', 'LUNGES'), ('Calf Raises', 'CALF_RAISES'), ('Leg Press', 'LEG_PRESS'), ('Deadlifts', 'DEADLIFTS')], default='sqauts', max_length=17, null=True),
        ),
    ]
